resources:
  - name: dbp_repo
    type: GitRepo
    configuration:
      gitProvider: myGithub                       # <-- replace with your integration
      path: jfrog/jfrog-pipelines-docker-sample    # <-- replace with your repository name
      branches:
        include: master

  - name: dbp_image
    type: Image
    configuration:
      registry: myArtifactory                                # <-- replace with your artifactory integration
      sourceRepository: quickstarts-docker-local               # <-- required if registry is Artifactory
      imageName: pipelines.jfrog.io/quickstarts-docker-local/dbp  # < -- replace with your image path and name
      imageTag: latest
      autoPull: true
      
  - name: dbp_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: myArtifactory
      buildName: dbp_build
      buildNumber: 1    

  - name: dbp_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: myArtifactory
      buildName: dbp_build
      buildNumber: 1
      
  - name: cron_trigger_docker
    type: CronTrigger
    configuration:
      interval: '0 2 * * *'       
      

pipelines:
  - name: Docker_Quickstart
    configuration:
      jfrogCliVersion: 2  
    steps:
      - name: docker_build_push
        type: Bash
        configuration:
          affinityGroup: dbp_group
          inputResources:
            - name: dbp_repo
            - name: cron_trigger_docker
          integrations:
            - name: myArtifactory                            # <-- replace with your artifactory integration
        execution:
          onStart:
              # - msg="Run description updated from step $step_id"
              # - update_run_description "$msg"  
              - update_run_description "Add custom text for every run. Example - Build and push Docker image to Artifactory."
          onExecute:
            - task: jfrog/docker-build@v0.0.1
              repository: pipelines-tasks-virtual
              input:
                resourceName: msgGit
                dockerImage: pipelines.jfrog.io/quickstarts-docker-local/dbp:${run_number}
                dockerFileName: Dockerfile
                dockerFileLocation: ""
            - task: jfrog/docker-push@v0.0.1
              repository: pipelines-tasks-virtual
              input:
                dockerImage: pipelines.jfrog.io/quickstarts-docker-local/dbp:${run_number}
                autoPublishBuildInfo: "true"
                xrayScan: "false"
                failOnScan: "false"           

      - name: publish_dbp_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_build_push
          outputResources:
            - name: dbp_build_info          

      - name: promote_dbp_build
        type: PromoteBuild
        configuration:
          targetRepository: quickstarts-target-local
          integrations:
            - name: myArtifactory
          inputResources:
            - name: dbp_build_info
          outputResources:
            - name: dbp_promoted_build_info
